/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreatePostLikeArgs } from "./CreatePostLikeArgs";
import { UpdatePostLikeArgs } from "./UpdatePostLikeArgs";
import { DeletePostLikeArgs } from "./DeletePostLikeArgs";
import { PostLikeFindManyArgs } from "./PostLikeFindManyArgs";
import { PostLikeFindUniqueArgs } from "./PostLikeFindUniqueArgs";
import { PostLike } from "./PostLike";
import { Post } from "../../post/base/Post";
import { User } from "../../user/base/User";
import { PostLikeService } from "../postLike.service";

@graphql.Resolver(() => PostLike)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PostLikeResolverBase {
  constructor(
    protected readonly service: PostLikeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PostLike",
    action: "read",
    possession: "any",
  })
  async _postLikesMeta(
    @graphql.Args() args: PostLikeFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [PostLike])
  @nestAccessControl.UseRoles({
    resource: "PostLike",
    action: "read",
    possession: "any",
  })
  async postLikes(
    @graphql.Args() args: PostLikeFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PostLike[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "PostLike",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => PostLike, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PostLike",
    action: "read",
    possession: "own",
  })
  async postLike(
    @graphql.Args() args: PostLikeFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PostLike | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "PostLike",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => PostLike)
  @nestAccessControl.UseRoles({
    resource: "PostLike",
    action: "create",
    possession: "any",
  })
  async createPostLike(
    @graphql.Args() args: CreatePostLikeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PostLike> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "PostLike",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"PostLike"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        post: {
          connect: args.data.post,
        },

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @graphql.Mutation(() => PostLike)
  @nestAccessControl.UseRoles({
    resource: "PostLike",
    action: "update",
    possession: "any",
  })
  async updatePostLike(
    @graphql.Args() args: UpdatePostLikeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PostLike | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "PostLike",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"PostLike"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          post: {
            connect: args.data.post,
          },

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PostLike)
  @nestAccessControl.UseRoles({
    resource: "PostLike",
    action: "delete",
    possession: "any",
  })
  async deletePostLike(
    @graphql.Args() args: DeletePostLikeArgs
  ): Promise<PostLike | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Post, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PostLike",
    action: "read",
    possession: "any",
  })
  async post(
    @graphql.Parent() parent: PostLike,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Post | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Post",
    });
    const result = await this.service.getPost(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PostLike",
    action: "read",
    possession: "any",
  })
  async user(
    @graphql.Parent() parent: PostLike,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
