/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateCommentLikeArgs } from "./CreateCommentLikeArgs";
import { UpdateCommentLikeArgs } from "./UpdateCommentLikeArgs";
import { DeleteCommentLikeArgs } from "./DeleteCommentLikeArgs";
import { CommentLikeFindManyArgs } from "./CommentLikeFindManyArgs";
import { CommentLikeFindUniqueArgs } from "./CommentLikeFindUniqueArgs";
import { CommentLike } from "./CommentLike";
import { Comment } from "../../comment/base/Comment";
import { User } from "../../user/base/User";
import { CommentLikeService } from "../commentLike.service";

@graphql.Resolver(() => CommentLike)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CommentLikeResolverBase {
  constructor(
    protected readonly service: CommentLikeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CommentLike",
    action: "read",
    possession: "any",
  })
  async _commentLikesMeta(
    @graphql.Args() args: CommentLikeFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [CommentLike])
  @nestAccessControl.UseRoles({
    resource: "CommentLike",
    action: "read",
    possession: "any",
  })
  async commentLikes(
    @graphql.Args() args: CommentLikeFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CommentLike[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "CommentLike",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => CommentLike, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CommentLike",
    action: "read",
    possession: "own",
  })
  async commentLike(
    @graphql.Args() args: CommentLikeFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CommentLike | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "CommentLike",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => CommentLike)
  @nestAccessControl.UseRoles({
    resource: "CommentLike",
    action: "create",
    possession: "any",
  })
  async createCommentLike(
    @graphql.Args() args: CreateCommentLikeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CommentLike> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "CommentLike",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CommentLike"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        comment: {
          connect: args.data.comment,
        },

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @graphql.Mutation(() => CommentLike)
  @nestAccessControl.UseRoles({
    resource: "CommentLike",
    action: "update",
    possession: "any",
  })
  async updateCommentLike(
    @graphql.Args() args: UpdateCommentLikeArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<CommentLike | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "CommentLike",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"CommentLike"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          comment: {
            connect: args.data.comment,
          },

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CommentLike)
  @nestAccessControl.UseRoles({
    resource: "CommentLike",
    action: "delete",
    possession: "any",
  })
  async deleteCommentLike(
    @graphql.Args() args: DeleteCommentLikeArgs
  ): Promise<CommentLike | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Comment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CommentLike",
    action: "read",
    possession: "any",
  })
  async comment(
    @graphql.Parent() parent: CommentLike,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Comment | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Comment",
    });
    const result = await this.service.getComment(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CommentLike",
    action: "read",
    possession: "any",
  })
  async user(
    @graphql.Parent() parent: CommentLike,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
